### ISSUE TITLE
可以发一下论文的地址吗

### ISSUE THREAD

**Issue by 20174376** [zifengcheng/CD-MRC#1]
您好，请问可以发一下原论文的地址吗？谢谢！

**Comment by zifengcheng** [comment]
您好，因为论文还在审稿过程中，暂时无法公布，感谢您的关注。

**Comment by 20174376** [comment]
> 您好，因为论文还在审稿过程中，暂时无法公布，感谢您的关注。

嗯嗯，好的，期待能早日见到您们的论文
